import json
import csv

def estimate_pose_from_imu_data(input_filename: str, output_filename: str):
    """
    Reads IMU data from a JSON Lines file and extracts pose (quaternion) information,
    saving it to a CSV file.

    Args:
        input_filename (str): Path to the input JSON Lines file.
        output_filename (str): Path for the output CSV file.
    """
    try:
        with open(input_filename, 'r') as infile, \
             open(output_filename, 'w', newline='') as outfile:

            # Create a CSV writer object
            csv_writer = csv.writer(outfile)

            # Write the header row to the CSV file
            csv_writer.writerow(['timestamp', 'q_w', 'q_x', 'q_y', 'q_z'])

            for line_num, line in enumerate(infile):
                line = line.strip()
                if not line:
                    continue  # Skip any empty lines

                try:
                    data_point = json.loads(line)
                    
                    timestamp = data_point.get('timestamp')
                    quaternion = data_point.get('quaternion')

                    # Validate that the required data is present and correctly formatted
                    if (timestamp is None or 
                        quaternion is None or 
                        not isinstance(quaternion, list) or 
                        len(quaternion) != 4):
                        
                        print(f"Warning: Skipping malformed line {line_num + 1}. "
                              f"Expected 'timestamp' and a quaternion of length 4.")
                        continue

                    # Write the timestamp and quaternion components to the CSV file
                    csv_writer.writerow([timestamp] + quaternion)

                except json.JSONDecodeError as e:
                    print(f"Warning: Could not parse JSON on line {line_num + 1}: {e}")
                    continue

        print(f"Successfully processed pose estimation. Results saved to '{output_filename}'.")

    except FileNotFoundError:
        print(f"Error: Input file '{input_filename}' was not found.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# --- Main execution block ---
if __name__ == "__main__":
    # The name of the input file generated by imu.py
    input_imu_data_file = 'bno055_data.json'
    
    # The desired name for the output pose estimation file
    output_pose_file = 'poses.csv'

    estimate_pose_from_imu_data(input_imu_data_file, output_pose_file)

