/better:
  ros__parameters:
    camera:
      # laser off
      i_laser_dot_brightness: 0
      i_nn_type: none
      i_pipeline_type: rgbd
      i_external_calibration_path: '/home/arco3/summer2024/cave_slam_2024/stereo/depthai_driver/config/calibration.json'
    left:
      i_board_socket_id: 1
      i_simulate_from_topic: true
      i_simulated_topic_name: '/oak/left/image_raw'
      i_disable_node: true
    right:
      i_board_socket_id: 2
      i_simulate_from_topic: true
      i_simulated_topic_name: '/oak/right/image_raw'
      i_disable_node: true
    rgb:
      i_simulate_from_topic: false
      i_simulated_topic_name: ''
    stereo:
      i_set_input_size: true
      i_input_width: 1280
      i_input_height: 720
      i_publish_topic: true
      i_left_socket_id: 1
      i_right_socket_id: 2
      i_enable_lazy_publisher: false

      i_subpixel: true
      i_extended_disp: false
      i_enable_decimation_filter: true
      i_enable_speckle_filter: false
      i_enable_spatial_filter: true
      i_enable_temporal_filter: false
      i_stereo_conf_threshold: 150


