/oak:
  ros__parameters:
    camera:
      # laser off
      i_laser_dot_brightness: 0
      i_nn_type: none
    left:
      i_publish_topic: true
    right:
      i_publish_topic: true
    stereo:
      i_subpixel: true