#!/usr/bin/env python3
# generated by chatgpt


import open3d as o3d
import numpy as np
import cv2
import os
import argparse


# -------------------- DEPTH LOADING --------------------
def load_depth_image(path, depth_scale, z_crop_value=255):
    depth = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if depth is None:
        raise RuntimeError(f"Failed to load {path}")

    # Ensure single channel
    if len(depth.shape) == 3:
        print(f"Warning: {path} has {depth.shape[2]} channels, using first channel")
        depth = depth[:, :, 0]

    # Remove invalid depth BEFORE scaling
    depth = depth.astype(np.float32)
    depth[depth == z_crop_value] = 0.0

    # Convert to meters
    depth /= depth_scale

    return depth


# -------------------- INTRINSICS --------------------
def create_intrinsics(width, height, fx, fy, cx, cy):
    intrinsics = o3d.camera.PinholeCameraIntrinsic()
    intrinsics.set_intrinsics(width, height, fx, fy, cx, cy)
    return intrinsics


# -------------------- DEPTH → POINT CLOUD --------------------
def depth_to_pointcloud(depth, intrinsics):
    depth_o3d = o3d.geometry.Image(depth)

    pcd = o3d.geometry.PointCloud.create_from_depth_image(
        depth_o3d,
        intrinsics,
        depth_scale=1.0,   # already scaled
        depth_trunc=5.0,
        stride=1
    )
    return pcd


# -------------------- SOR FILTER --------------------
def apply_sor(pcd, nb_neighbors, std_ratio):
    if len(pcd.points) == 0:
        return pcd

    cl, ind = pcd.remove_statistical_outlier(
        nb_neighbors=nb_neighbors,
        std_ratio=std_ratio
    )
    return pcd.select_by_index(ind)


# -------------------- PROCESS SINGLE FRAME --------------------
def process_frame(path, args):
    depth = load_depth_image(path, args.depth_scale, args.z_crop_value)
    h, w = depth.shape

    intrinsics = create_intrinsics(w, h, args.fx, args.fy, args.cx, args.cy)
    pcd = depth_to_pointcloud(depth, intrinsics)

    if not args.disable_sor:
        pcd = apply_sor(pcd, args.sor_nb_neighbors, args.sor_std_ratio)

    return pcd

def add_fake_color(pcd):
    n = len(pcd.points)
    colors = np.ones((n, 3))  # white
    pcd.colors = o3d.utility.Vector3dVector(colors)
    return pcd

# -------------------- MAIN --------------------
def main():
    parser = argparse.ArgumentParser()

    # Root directory (contains Extracted_Images)
    parser.add_argument("root_dir", help="Root directory containing Extracted_Images")

    # Intrinsics (easy to tweak)
    parser.add_argument("--fx", type=float, default=75.0)
    parser.add_argument("--fy", type=float, default=75.0)
    parser.add_argument("--cx", type=float, default=50.0)
    parser.add_argument("--cy", type=float, default=50.0)

    parser.add_argument("--depth_scale", type=float, default=1000.0)
    parser.add_argument("--z_crop_value", type=float, default=255)

    # SOR options
    parser.add_argument("--disable_sor", action="store_true")
    parser.add_argument("--sor_nb_neighbors", type=int, default=20)
    parser.add_argument("--sor_std_ratio", type=float, default=1.0)

    # Mode
    parser.add_argument("--save_ply", action="store_true",
                        help="Save PLY files instead of showing viewer")

    args = parser.parse_args()

    image_dir = os.path.join(args.root_dir, "Extracted_Images")
    output_dir = os.path.join(args.root_dir, "Filtered_Point_Clouds")

    if not os.path.exists(image_dir):
        print(f"Error: {image_dir} does not exist")
        return

    if args.save_ply:
        os.makedirs(output_dir, exist_ok=True)

    files = sorted([
        f for f in os.listdir(image_dir)
        if f.endswith(".png") or f.endswith(".tiff")
    ])

    if not files:
        print("No images found.")
        return

    # -------------------- SAVE MODE --------------------
    if args.save_ply:
        print(f"Saving PLY files to: {output_dir}")

        for i, fname in enumerate(files):
            path = os.path.join(image_dir, fname)
            print(f"[{i+1}/{len(files)}] Processing {fname}")

            pcd = process_frame(path, args)
            pcd = add_fake_color(pcd)

            if len(pcd.points) == 0:
                print(f"Warning: empty cloud for {fname}")
                continue

            out_path = os.path.join(output_dir, f"frame{str(i).zfill(5)}.ply")
            o3d.io.write_point_cloud(out_path, pcd, write_ascii=True)

        print("Done.")
        return

    # -------------------- VIEWER MODE --------------------
    vis = o3d.visualization.VisualizerWithKeyCallback()
    vis.create_window()

    idx = [0]

    def update(vis, initial):
        vis.clear_geometries()

        fname = files[idx[0]]
        path = os.path.join(image_dir, fname)
        print(f"Showing {fname}")

        pcd = process_frame(path, args)
        vis.add_geometry(pcd, reset_bounding_box=initial)

    def next_frame(vis):
        idx[0] = (idx[0] + 1) % len(files)
        update(vis, False)
        return False

    def prev_frame(vis):
        idx[0] = (idx[0] - 1) % len(files)
        update(vis, False)
        return False

    vis.register_key_callback(ord("N"), next_frame)
    vis.register_key_callback(ord("B"), prev_frame)

    update(vis, True)

    print("\nControls:")
    print("  N → next frame")
    print("  B → previous frame")

    vis.run()
    vis.destroy_window()


if __name__ == "__main__":
    main()