#!/usr/bin/env python3
# generated by chatgpt

import argparse
import os
import re
import numpy as np
import open3d as o3d


def parse_transform_filename(filename):
    match = re.match(r"icp(\d{5})_(\d{5})\.csv", filename)
    if not match:
        return None
    return int(match.group(1)), int(match.group(2))


def load_transform(path):
    T = np.loadtxt(path, delimiter=',')
    if T.shape != (4, 4):
        raise ValueError(f"{path} is not a 4x4 matrix")
    return T


def load_cloud(clouds_dir, frame_id):
    path = os.path.join(clouds_dir, f"frame{frame_id:05d}.ply")
    if not os.path.exists(path):
        raise FileNotFoundError(path)
    return o3d.io.read_point_cloud(path)


class Viewer:
    def __init__(self, transforms, transforms_dir, clouds_dir):
        self.transforms = transforms
        self.transforms_dir = transforms_dir
        self.clouds_dir = clouds_dir
        self.idx = 0

        self.vis = o3d.visualization.VisualizerWithKeyCallback()
        self.vis.create_window("ICP Viewer", width=1000, height=800)

        # Register keys
        self.vis.register_key_callback(ord("N"), self.next)
        self.vis.register_key_callback(ord("B"), self.prev)
        self.vis.register_key_callback(256, self.quit)  # ESC

        self.geometry = None
        self.load_current()

    def load_current(self):
        if self.geometry is not None:
            self.vis.remove_geometry(self.geometry, reset_bounding_box=False)

        fname = self.transforms[self.idx]
        f1, f2 = parse_transform_filename(fname)

        print(f"\n[{self.idx+1}/{len(self.transforms)}] {fname}")
        print(f"Frame {f1} -> Frame {f2}")

        T_path = os.path.join(self.transforms_dir, fname)

        try:
            T = load_transform(T_path)
            pcd1 = load_cloud(self.clouds_dir, f1)
            pcd2 = load_cloud(self.clouds_dir, f2)
        except Exception as e:
            print(f"Error: {e}")
            return

        # Apply transform
        pcd2.transform(T)

        # Color
        pcd1.paint_uniform_color([1, 0, 0])  # red
        pcd2.paint_uniform_color([0, 1, 0])  # green

        self.geometry = pcd1 + pcd2

        self.vis.add_geometry(self.geometry, reset_bounding_box=True)

    def next(self, vis):
        if self.idx < len(self.transforms) - 1:
            self.idx += 1
            self.load_current()
        return False

    def prev(self, vis):
        if self.idx > 0:
            self.idx -= 1
            self.load_current()
        return False

    def quit(self, vis):
        vis.close()
        return False

    def run(self):
        print("Controls:")
        print("  N → next")
        print("  B → previous")
        print("  ESC → quit")

        self.vis.run()
        self.vis.destroy_window()


def main():
    parser = argparse.ArgumentParser(description="Interactive ICP transform viewer")
    parser.add_argument("root", help="Root directory")
    args = parser.parse_args()

    transforms_dir = os.path.join(args.root, "transforms")
    clouds_dir = os.path.join(args.root, "Filtered_Point_Clouds")

    files = sorted(os.listdir(transforms_dir))
    transforms = [f for f in files if parse_transform_filename(f)]

    if not transforms:
        raise RuntimeError("No valid transform files found")

    viewer = Viewer(transforms, transforms_dir, clouds_dir)
    viewer.run()


if __name__ == "__main__":
    main()