# name: Python CI/CD
#
# on:
#   push:
#     branches:
#       - main
#
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10' # TODO: make sure this is ok
#
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#
#       - name: Run tests # TODO: replace with whatever test tool we end up using
#         run: |
#           python -m pytest
#
#   release:
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Generate version
#         run: |
#           # version format: YYYYMMDD-HHMMSS
#           VERSION=$(date +"%Y%m%d-%H%M%S")
#           echo "::set-env::VERSION=$VERSION"
#
#       - name: Create GitHub Release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ env.VERSION }}
#           release_name: Release ${{ env.VERSION }}
#           body: |
#             Automated release after successful tests.
#           draft: false
#           prerelease: false
